import type { Metadata } from 'next';

import Providers from '@/components/providers';
import './globals.css';
import TopNav from '@/components/navbar/TopNav';
import Container from '@/components/Container';

export const metadata: Metadata = {
	title: 'Next Match',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<TopNav />
					<Container>{children}</Container>
				</Providers>
			</body>
		</html>
	);
}
